language: nix

before_install:
- nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
- nix-channel --update

script:
- nix-shell -p 'idrisPackages.with-packages [ ((import <nixpkgs> {}).idrisPackages.callPackage ./quantities.nix {}) ]' --run "idris --check examples/Documentation.idr examples/Game.idr"